<!DOCTYPE html>
<html>
<head>
  <title>Firebase Email Login</title>
</head>
<body>
  <h2>Login</h2>
  <form id="loginForm">
    <input type="email" id="email" placeholder="Enter email" required />
    <input type="password" id="password" placeholder="Enter password" required />
    <button type="submit">Login</button>
  </form>
  
  <h2>Register</h2>
  <form id="registerForm">
    <input type="email" id="regEmail" placeholder="Enter email" required />
    <input type="password" id="regPassword" placeholder="Enter password" required />
    <button type="submit">Register</button>
  </form>

  <script src="https://www.gstatic.com/firebasejs/10.5.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/10.5.0/firebase-auth.js"></script>
  <script>
    const firebaseConfig = {
      apiKey: "AIzaSyA3nK6zZSc0U5bbcBIwlEXJmUhVyZ-VPSo",
  authDomain: "gidna-mat.firebaseapp.com",
  projectId: "gidna-mat",
  storageBucket: "gidna-mat.firebasestorage.app",
  messagingSenderId: "105419890575",
  appId: "1:105419890575:web:f84d810576f3f6c24635fa",
  measurementId: "G-R329STG99R"
    };

    firebase.initializeApp(firebaseConfig);
    const auth = firebase.auth();

    // Login
    document.getElementById('loginForm').addEventListener('submit', (e) => {
      e.preventDefault();
      const email = document.getElementById('email').value;
      const password = document.getElementById('password').value;

      auth.signInWithEmailAndPassword(email, password)
        .then((userCredential) => {
          alert(
>
